name: 'debug'

on:
  # push:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_num:
        description: Pull Request Number (optional)
        required: false

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        if: ${{ inputs.pr_num == '' }}
        uses: actions/checkout@v3

      - name: Checkout PR ${{ inputs.pr_num }}
        if: ${{ inputs.pr_num != '' }}
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ inputs.pr_num }}/merge"

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'


      - name: Print all environment variables
        run:  env
