name: 'Make contribs-dict.txt'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  contributors_to_file:
    runs-on: ubuntu-latest
    env: 
      GITHUB_REPOSITORY:  PathOfBuildingCommunity/PathOfBuilding
    name: Make contribs-dict.txt
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v3
      with:
        repository:  ${{ env.GITHUB_REPOSITORY }}
    - name: Update contributors
      id: update_contributors
      uses: TheLastProject/contributors-to-file-action@v3
      with:
        file_in_repo: contribs-dict.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Make contribs-dict.txt"
        branch-suffix: timestamp
