name: Auto-update contribs-dict

on:
  workflow_dispatch:
  schedule:
    - cron: "1 17 * * *"

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: nightblade/list-contributors-simple@v1
        with:
          repo_names: |
            PathOfBuildingCommunity/PathOfBuilding
            PathOfBuildingCommunity/PathOfBuilding-PoE2
          output_file: "contributors.txt"
          access_token: ${{secrets.GITHUB_TOKEN}}

      - run: |
          cat contribs-dict.txt >> contributors.txt
          export LC_ALL=C && sort -fu contributors.txt | grep -v "github-actions" > contribs-dict.txt
          wc -l contribs-dict.txt
          rm contributors.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-commit contribs-dict.txt
